// Variables

male_novelist = [
["boobs",
"a bust",
"a butt",
"lips",
"an ass",
"breasts",
"hair",
"eyes",
"a voice",
"curves",
"a rump",
"legs",
"a rear end",
"mammaries",
"jugs",
"calves",
"a badonkadonk",
"gams",
"knockers",
"a complexion",
"a pout",
"hooters",
"a booty",
"cheeks",
"thighs",
"tresses"],

["silken",
"creamy",
"shiny",
"ripe",
"juicy",
"middle—aged",
"rippling",
"wrinkled",
"luscious",
"frigid",
"voluptuous",
"expensive",
"plump",
"bountiful",
"tempestuous",
"withered",
"haughty",
"shrill",
"fat",
"dewy",
"soft",
"wiry",
"gleaming",
"withholding",
"bulbous",
"brittle"],

["kitten",
"mountain",
"pillow",
"ice cream cone",
"tulip",
"lake",
"fortress",
"lemon",
"popsicle",
"librarian",
"python",
"pony",
"melon",
"bedsheet",
"muffin",
"bunny rabbit",
"fish",
"princess",
"ghost",
"waterfall",
"mango",
"harpy",
"ship",
"nun",
"berry",
"car"],
	
["longed",
"lusted",
"wished",
"wanted",
"resolved",
"dared",
"detested",
"trembled",
"thirsted",
"expected",
"planned",
"deigned",
"proposed",
"shuddered",
"refused",
"hated",
"scorned",
"dreaded",
"did not care",
"ached",
"intended",
"hungered",
"craved",
"hankered",
"needed",
"pined"],

["ravish",
"climb",
"invade",
"grope",
"marry",
"raw dog it with",
"caress",
"proposition",
"correct",
"emotionally manipulate",
"spar with",
"compliment",
"hire",
"booty call",
"mansplain to",
"insult",
"date",
"teabag",
"ignore",
"fondle",
"worship",
"examine",
"manhandle",
"touch",
"admire",
"demand things from"]
]

novel_pitch = [
["edge-of-your-seat",
"keenly observed",
"lyrical",
"profound",
"erotic",
"inspiring",
"razor-sharp",
"heartrending",
"dream-like",
"darkly comic",
"uncompromising",
"courageous",
"compulsively readable",
"unﬂinching",
"ﬁercely honest",
"richly drawn",
"unforgettable",
"riveting",
"high-voltage",
"psycho-sexual",
"riotously funny",
"passionate",
"surreal",
"dystopian",
"hysterical",
"meditative"],

["thriller",
"meditation",
"coming of age siory",
"iamily drama",
"war epic",
"episotolary novel",
"romance",
"tragedy",
"story",
"tour de force",
"comedy",
"noir",
"instant classic",
"fairy tale",
"autobiographical novel",
"romp",
"fictional memoir",
"trilogy",
"detective novel",
"page-turner",
"tragicomedy",
"murder mystery",
"novel in stories",
"historical novel",
"graphic novel",
"saga"],

["depressed",
"wealthy",
"doomed",
"exuberant",
"agoraphobic",
"maladjusted",
"misanthropic",
"alcoholic",
"young",
"philosophical",
"hopelessly romantic",
"hyper—sexual",
"precocious",
"unlucky",
"quixotic",
"desperate",
"refugee",
"dissatisﬁed",
"bored",
"morally compromised",
"lovesick",
"drug-addled",
"jilted",
"vengeful",
"overbearing",
"closeted"],

["man's",
"orphan's",
"daughter's",
"mothers",
"adoloscent's",
"soldiers",
"student's",
"widow's",
"woman's",
"professors",
"divorcee's",
"adventurer's",
"extended family's",
"child's",
"mistress's",
"dictators",
"vampire's",
"ghost's",
"starship captain's",
"doctor's",
"writer's",
"private investigator's",
"couple's",
"coven's",
"murder detective's",
"octogenarian's"],

["adventure",
"commitment",
"deshe",
"devotion",
"dream",
"effort",
"strategy",
"pains",
"failure",
"inability",
"journey",
"mission",
"not-so-secret desire",
"quest",
"endeavour",
"secret longing",
"struggle",
"vacation",
"wish",
"expedition",
"plan",
"scheme",
"resolve",
"project",
"promise",
"battle"],

["re-awaken",
"come to grips with",
"grapple with",
"understand",
"explore",
"accept",
"overcome",
"avenge",
"pursue",
"defend",
"undertake",
"discover",
"contemplate",
"transcend",
"withdraw from",
"avoid",
"betray",
"circumvent",
"confront",
"expose",
"give up",
"investigate",
"navigate",
"reconnect with",
"embrace",
"reconcile to"],

["fear of spiders",
"adoption",
"traumatic childhood",
"mother’s deaih",
"sexless marriage",
"Oedipal complex",
"feminism",
"religious upbringing",
"political apathy",
"biological clock",
"ugly divorce",
"writer's block",
"toxic friendships",
"eating disorder",
"own birth",
"cancer",
"23andMe results",
"privilege",
"untimely death",
"social media addiction",
"spiritual evolution",
"secret second family",
"sexual awakening",
"Amazon reviews",
"father's murder",
"disinheritance"]
]

mapping = {
	"a": 0,
	"b": 1,
	"c": 2,
	"d": 3,
	"e": 4,
	"f": 5,
	"g": 6,
	"h": 7,
	"i": 8,
	"j": 9,
	"k": 10,
	"l": 11,
	"m": 12,
	"n": 13,
	"o": 14,
	"p": 15,
	"q": 16,
	"r": 17,
	"s": 18,
	"t": 19,
	"u": 20,
	"v": 21,
	"w": 22,
	"x": 23,
	"y": 24,
	"z": 25
}



document.addEventListener("DOMContentLoaded", function(event){
	function mapLetterToWord() {
		name = this.value;
		letters = name.split('');
		mn_words = []
		np_words = []
		letters.forEach(function callback(letter, index) {
			alphaPosition = mapping[letter];
			// index is used to select the right list to retrieve from
			// alphaPosition is then used to retrieve the right word
			if (index < male_novelist.length) {
				mn_words.push(male_novelist[index][alphaPosition]);
			}
			if (index < novel_pitch.length) {
				np_words.push(novel_pitch[index][alphaPosition]);
			}
			// now take the arrays and spit them into the blanks
			mn_blanks = document.getElementsByName("mn");
			for (var i = 0; i < mn_blanks.length; i++) {
				mn_blanks[i].innerHTML = (mn_words[i] == undefined ? "_____" : mn_words[i]);
			}
			np_blanks = document.getElementsByName("np");
			for (var i = 0; i < np_blanks.length; i++) {
				np_blanks[i].innerHTML = (np_words[i] == undefined ? "_____" : np_words[i]);
			}
		});
	}

	formElement = document.getElementById("fullname");
	formElement.addEventListener('keyup', mapLetterToWord, false);
});
